### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by fuzzy-focus** [jcupitt/argh-steroids#2]
Hey, cool project.
Runs mostly fine in Python3.4 with Pygame 1.9.2 after one little change:
particles.py:Line 359:
was:  keys = self.particles.keys()
should be:   keys = list(self.particles.keys())

As dict.keys() now returns a view that automatically updates when the dict changes it is no longer possible to iterate over the keys and changing the dict at the same time. Making a copy of the initial keys list fixes that.

Everything else ran wonderfully.

**Comment by jcupitt** [comment]
Oh, nice catch. I've fixed it, thanks very much!
